import { jsPDF } from 'jspdf';
import { Analysis } from '../types.ts';

/**
 * Exports a beautifully formatted PDF report of the Skill Gap Analysis and Learning Roadmap.
 */
export function exportAnalysisToPDF(analysis: Analysis) {
  // Initialize standard A4 PDF: Portrait, millimeters, A4 size (210 x 277 mm)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const marginX = 15;
  const contentWidth = pageWidth - marginX * 2; // 180mm printable width
  let currentY = 20;
  let pageNum = 1;

  // Global Theme Colors (RGB)
  const colors = {
    primary: [30, 41, 59] as [number, number, number],      // Slate 800 (Dark Slate)
    accent: [37, 99, 235] as [number, number, number],      // Blue 600 (Brand Accent)
    secondary: [71, 85, 105] as [number, number, number],   // Slate 600 (Body text)
    lightBg: [248, 250, 252] as [number, number, number],   // Slate 50 (Section backgrounds)
    border: [226, 232, 240] as [number, number, number],    // Slate 200 (Lines & Borders)
    matched: [37, 99, 235] as [number, number, number],     // Blue 600
    partial: [217, 119, 6] as [number, number, number],     // Amber 600
    missing: [225, 29, 72] as [number, number, number],     // Rose 600
  };

  // Helper: Draw Header & Footer on each page
  const drawPageDecorations = (document: jsPDF, page: number) => {
    // Top Accent bar
    document.setFillColor(...colors.accent);
    document.rect(0, 0, pageWidth, 4, 'F');

    // Header Meta
    document.setFont('Helvetica', 'normal');
    document.setFontSize(8);
    document.setTextColor(148, 163, 184); // Slate 400
    document.text('SKILL GAP AGENT — SEMANTIC EVALUATION REPORT', marginX, 10);
    
    // Page Number Footer
    document.setDrawColor(...colors.border);
    document.line(marginX, pageHeight - 15, pageWidth - marginX, pageHeight - 15);
    document.text(`Page ${page}`, pageWidth - marginX - 12, pageHeight - 10);
    document.text(`Generated by Skill Gap Agent (id: ${analysis.id})`, marginX, pageHeight - 10);
  };

  // Helper: Safely advance Y and check for page boundaries
  const checkPageSpace = (heightNeeded: number): void => {
    const bottomLimit = pageHeight - 22; // Leave space for footer
    if (currentY + heightNeeded > bottomLimit) {
      doc.addPage();
      pageNum += 1;
      currentY = 20;
      drawPageDecorations(doc, pageNum);
    }
  };

  // Initialize first page decorations
  drawPageDecorations(doc, pageNum);

  // ==========================================
  // 1. BRAND LOGO & TITLE
  // ==========================================
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...colors.primary);
  doc.text('Skill Gap Agent', marginX, currentY);
  
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...colors.accent);
  doc.text('PROFESSIONAL EVALUATION REPORT', marginX, currentY + 5);

  currentY += 14;

  // Divider Line
  doc.setDrawColor(...colors.border);
  doc.setLineWidth(0.5);
  doc.line(marginX, currentY, pageWidth - marginX, currentY);
  currentY += 8;

  // ==========================================
  // 2. METADATA SECTION
  // ==========================================
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...colors.primary);
  doc.text(analysis.jobTitle, marginX, currentY);
  currentY += 5;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...colors.secondary);
  const formattedDate = new Date(analysis.createdAt).toLocaleString();
  doc.text(`Candidate Analysis ID: ${analysis.id}`, marginX, currentY);
  doc.text(`Created on: ${formattedDate}`, marginX, currentY + 4.5);
  currentY += 12;

  // ==========================================
  // 3. READINESS SCORE CARD (Visual Box)
  // ==========================================
  checkPageSpace(32);
  doc.setFillColor(...colors.lightBg);
  doc.setDrawColor(...colors.border);
  doc.roundedRect(marginX, currentY, contentWidth, 24, 2, 2, 'FD');

  // Readiness text & score
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.text('READINESS ASSESSMENT', marginX + 6, currentY + 7);

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...colors.accent);
  doc.text(`${analysis.readinessScore}%`, marginX + 6, currentY + 17);

  // Explanatory comment in score card
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...colors.primary);
  
  let readinessFeedback = '';
  if (analysis.readinessScore >= 80) {
    readinessFeedback = 'Excellent alignment! High readiness level detected.';
  } else if (analysis.readinessScore >= 55) {
    readinessFeedback = 'Strong base. Recommended to close a few key gaps.';
  } else {
    readinessFeedback = 'Substantial gaps. Focus heavily on learning roadmap.';
  }
  
  doc.text(readinessFeedback, marginX + 38, currentY + 14);
  currentY += 32;

  // ==========================================
  // 4. GAP SUMMARY (Executive Summary)
  // ==========================================
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...colors.primary);
  doc.text('EXECUTIVE GAP SUMMARY', marginX, currentY);
  currentY += 5;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...colors.secondary);
  const splitSummary = doc.splitTextToSize(analysis.summary, contentWidth);
  checkPageSpace(splitSummary.length * 5 + 4);
  doc.text(splitSummary, marginX, currentY);
  currentY += splitSummary.length * 5 + 8;

  // ==========================================
  // 5. CORE ALIGNMENTS & STRENGTHS
  // ==========================================
  const strengthsList = Array.isArray(analysis.strengths)
    ? analysis.strengths
    : typeof analysis.strengths === 'string'
      ? (analysis.strengths as string).split(',').filter(Boolean)
      : [];

  if (strengthsList.length > 0) {
    checkPageSpace(15);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...colors.primary);
    doc.text('CORE ALIGNMENTS & STRENGTHS', marginX, currentY);
    currentY += 6;

    strengthsList.forEach((strength) => {
      const bulletText = `\u2022  ${strength.trim()}`;
      const splitBullet = doc.splitTextToSize(bulletText, contentWidth - 4);
      checkPageSpace(splitBullet.length * 4.5 + 2);
      
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...colors.secondary);
      doc.text(splitBullet, marginX + 2, currentY);
      currentY += splitBullet.length * 4.5 + 1.5;
    });
    currentY += 6;
  }

  // ==========================================
  // 6. SEMANTIC SKILL PROFILE (Matched, Partial, Missing)
  // ==========================================
  checkPageSpace(20);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...colors.primary);
  doc.text('SEMANTIC SKILL PROFILE', marginX, currentY);
  currentY += 6;

  const skills = analysis.skills || [];
  const matched = skills.filter((s) => s.status === 'matched').map(s => s.skillName);
  const partial = skills.filter((s) => s.status === 'partial').map(s => s.skillName);
  const missing = skills.filter((s) => s.status === 'missing').map(s => s.skillName);

  // Helper to draw boxed lists of skills
  const drawSkillCategory = (title: string, list: string[], tagColor: [number, number, number]) => {
    if (list.length === 0) return;
    
    checkPageSpace(16);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(...tagColor);
    doc.text(title, marginX, currentY);
    currentY += 5;

    // Draw wrapped skills list as horizontal tags if possible, or nicely bulleted list.
    // Given layout constraints, a dense comma-separated or inline wrapped flow is very elegant.
    const joinedText = list.join('   \u2022   ');
    const splitJoinedText = doc.splitTextToSize(joinedText, contentWidth);
    
    checkPageSpace(splitJoinedText.length * 4.5 + 4);
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...colors.secondary);
    doc.text(splitJoinedText, marginX, currentY);
    currentY += splitJoinedText.length * 4.5 + 5;
  };

  drawSkillCategory(`MATCHED SKILLS (${matched.length})`, matched, colors.matched);
  drawSkillCategory(`PARTIALLY MATCHED SKILLS (${partial.length})`, partial, colors.partial);
  drawSkillCategory(`CRITICAL MISSING SKILLS (${missing.length})`, missing, colors.missing);
  currentY += 4;

  // ==========================================
  // 7. DETAILED LEARNING ROADMAP
  // ==========================================
  if (analysis.roadmap && analysis.roadmap.length > 0) {
    checkPageSpace(15);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...colors.primary);
    doc.text('PRIORITIZED LEARNING ROADMAP', marginX, currentY);
    currentY += 7;

    analysis.roadmap.forEach((item, idx) => {
      // Approximate height needed: Title, Priority, Reason text, Resources (which can wrap)
      // Let's do a strict safety check of at least 35mm
      checkPageSpace(35);

      // Draw Roadmap Item Card Background
      const itemYStart = currentY;
      
      // We will draw the card header
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...colors.primary);
      const headerTitle = `${idx + 1}. Skill Gap: ${item.skill}`;
      doc.text(headerTitle, marginX, currentY);
      
      // Priority Badge Text on the right
      const priorityText = `${item.priority.toUpperCase()} PRIORITY`;
      const badgeWidth = doc.getTextWidth(priorityText);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(8.5);
      if (item.priority === 'High') {
        doc.setTextColor(...colors.missing);
      } else if (item.priority === 'Medium') {
        doc.setTextColor(...colors.partial);
      } else {
        doc.setTextColor(...colors.matched);
      }
      doc.text(priorityText, pageWidth - marginX - badgeWidth, currentY);
      currentY += 5.5;

      // Reason explanation
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...colors.secondary);
      const splitReason = doc.splitTextToSize(item.reason, contentWidth - 4);
      checkPageSpace(splitReason.length * 4.5 + 4);
      doc.text(splitReason, marginX + 2, currentY);
      currentY += splitReason.length * 4.5 + 4;

      // Recommended resources
      if (item.resources && item.resources.length > 0) {
        checkPageSpace(10);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139); // Slate 500
        doc.text('RECOMMENDED RESOURCES:', marginX + 2, currentY);
        currentY += 4;

        item.resources.forEach((resource) => {
          const splitResource = doc.splitTextToSize(`- ${resource}`, contentWidth - 8);
          checkPageSpace(splitResource.length * 4.2 + 2);
          doc.setFont('Helvetica', 'normal');
          doc.setFontSize(8.5);
          doc.setTextColor(...colors.accent); // Accent color for URLs/resource titles
          doc.text(splitResource, marginX + 4, currentY);
          currentY += splitResource.length * 4.2 + 1;
        });
      }

      // Border line under each roadmap item to visually separate them
      currentY += 3;
      doc.setDrawColor(...colors.border);
      doc.setLineWidth(0.2);
      doc.line(marginX, currentY, pageWidth - marginX, currentY);
      currentY += 6;
    });
  }

  // Save the PDF
  const safeTitle = analysis.jobTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  doc.save(`skill-gap-analysis-${safeTitle}.pdf`);
}
